# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protBuffDef.proto',
  package='kodiaq_data',
  serialized_pb='\n\x11protBuffDef.proto\x12\x0bkodiaq_data\"\xcc\x01\n\x05\x45vent\x12\x0e\n\x06number\x18\x01 \x02(\x03\x12\x0c\n\x04time\x18\x02 \x02(\x04\x12)\n\x06module\x18\x03 \x03(\x0b\x32\x19.kodiaq_data.Event.Module\x1az\n\x06Module\x12\x10\n\x08moduleID\x18\x01 \x02(\x05\x12\x32\n\x07\x63hannel\x18\x02 \x03(\x0b\x32!.kodiaq_data.Event.Module.Channel\x1a*\n\x07\x43hannel\x12\x11\n\tchannelID\x18\x01 \x02(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c')




_EVENT_MODULE_CHANNEL = descriptor.Descriptor(
  name='Channel',
  full_name='kodiaq_data.Event.Module.Channel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='channelID', full_name='kodiaq_data.Event.Module.Channel.channelID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='kodiaq_data.Event.Module.Channel.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=197,
  serialized_end=239,
)

_EVENT_MODULE = descriptor.Descriptor(
  name='Module',
  full_name='kodiaq_data.Event.Module',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='moduleID', full_name='kodiaq_data.Event.Module.moduleID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='channel', full_name='kodiaq_data.Event.Module.channel', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EVENT_MODULE_CHANNEL, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=117,
  serialized_end=239,
)

_EVENT = descriptor.Descriptor(
  name='Event',
  full_name='kodiaq_data.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='number', full_name='kodiaq_data.Event.number', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='time', full_name='kodiaq_data.Event.time', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='module', full_name='kodiaq_data.Event.module', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EVENT_MODULE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=239,
)

_EVENT_MODULE_CHANNEL.containing_type = _EVENT_MODULE;
_EVENT_MODULE.fields_by_name['channel'].message_type = _EVENT_MODULE_CHANNEL
_EVENT_MODULE.containing_type = _EVENT;
_EVENT.fields_by_name['module'].message_type = _EVENT_MODULE
DESCRIPTOR.message_types_by_name['Event'] = _EVENT

class Event(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Module(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    
    class Channel(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _EVENT_MODULE_CHANNEL
      
      # @@protoc_insertion_point(class_scope:kodiaq_data.Event.Module.Channel)
    DESCRIPTOR = _EVENT_MODULE
    
    # @@protoc_insertion_point(class_scope:kodiaq_data.Event.Module)
  DESCRIPTOR = _EVENT
  
  # @@protoc_insertion_point(class_scope:kodiaq_data.Event)

# @@protoc_insertion_point(module_scope)
