// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protBuffDef.proto

#ifndef PROTOBUF_protBuffDef_2eproto__INCLUDED
#define PROTOBUF_protBuffDef_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace kodiaq_data {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_protBuffDef_2eproto();
void protobuf_AssignDesc_protBuffDef_2eproto();
void protobuf_ShutdownFile_protBuffDef_2eproto();

class Event;
class Event_Module;
class Event_Module_Channel;

// ===================================================================

class Event_Module_Channel : public ::google::protobuf::Message {
 public:
  Event_Module_Channel();
  virtual ~Event_Module_Channel();
  
  Event_Module_Channel(const Event_Module_Channel& from);
  
  inline Event_Module_Channel& operator=(const Event_Module_Channel& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Event_Module_Channel& default_instance();
  
  void Swap(Event_Module_Channel* other);
  
  // implements Message ----------------------------------------------
  
  Event_Module_Channel* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Event_Module_Channel& from);
  void MergeFrom(const Event_Module_Channel& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 channelID = 1;
  inline bool has_channelid() const;
  inline void clear_channelid();
  static const int kChannelIDFieldNumber = 1;
  inline ::google::protobuf::int32 channelid() const;
  inline void set_channelid(::google::protobuf::int32 value);
  
  // required bytes data = 2;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 2;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  
  // @@protoc_insertion_point(class_scope:kodiaq_data.Event.Module.Channel)
 private:
  inline void set_has_channelid();
  inline void clear_has_channelid();
  inline void set_has_data();
  inline void clear_has_data();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* data_;
  ::google::protobuf::int32 channelid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_protBuffDef_2eproto();
  friend void protobuf_AssignDesc_protBuffDef_2eproto();
  friend void protobuf_ShutdownFile_protBuffDef_2eproto();
  
  void InitAsDefaultInstance();
  static Event_Module_Channel* default_instance_;
};
// -------------------------------------------------------------------

class Event_Module : public ::google::protobuf::Message {
 public:
  Event_Module();
  virtual ~Event_Module();
  
  Event_Module(const Event_Module& from);
  
  inline Event_Module& operator=(const Event_Module& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Event_Module& default_instance();
  
  void Swap(Event_Module* other);
  
  // implements Message ----------------------------------------------
  
  Event_Module* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Event_Module& from);
  void MergeFrom(const Event_Module& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef Event_Module_Channel Channel;
  
  // accessors -------------------------------------------------------
  
  // required int32 moduleID = 1;
  inline bool has_moduleid() const;
  inline void clear_moduleid();
  static const int kModuleIDFieldNumber = 1;
  inline ::google::protobuf::int32 moduleid() const;
  inline void set_moduleid(::google::protobuf::int32 value);
  
  // repeated .kodiaq_data.Event.Module.Channel channel = 2;
  inline int channel_size() const;
  inline void clear_channel();
  static const int kChannelFieldNumber = 2;
  inline const ::kodiaq_data::Event_Module_Channel& channel(int index) const;
  inline ::kodiaq_data::Event_Module_Channel* mutable_channel(int index);
  inline ::kodiaq_data::Event_Module_Channel* add_channel();
  inline const ::google::protobuf::RepeatedPtrField< ::kodiaq_data::Event_Module_Channel >&
      channel() const;
  inline ::google::protobuf::RepeatedPtrField< ::kodiaq_data::Event_Module_Channel >*
      mutable_channel();
  
  // @@protoc_insertion_point(class_scope:kodiaq_data.Event.Module)
 private:
  inline void set_has_moduleid();
  inline void clear_has_moduleid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::kodiaq_data::Event_Module_Channel > channel_;
  ::google::protobuf::int32 moduleid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_protBuffDef_2eproto();
  friend void protobuf_AssignDesc_protBuffDef_2eproto();
  friend void protobuf_ShutdownFile_protBuffDef_2eproto();
  
  void InitAsDefaultInstance();
  static Event_Module* default_instance_;
};
// -------------------------------------------------------------------

class Event : public ::google::protobuf::Message {
 public:
  Event();
  virtual ~Event();
  
  Event(const Event& from);
  
  inline Event& operator=(const Event& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Event& default_instance();
  
  void Swap(Event* other);
  
  // implements Message ----------------------------------------------
  
  Event* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Event& from);
  void MergeFrom(const Event& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef Event_Module Module;
  
  // accessors -------------------------------------------------------
  
  // required int64 number = 1;
  inline bool has_number() const;
  inline void clear_number();
  static const int kNumberFieldNumber = 1;
  inline ::google::protobuf::int64 number() const;
  inline void set_number(::google::protobuf::int64 value);
  
  // required uint64 time = 2;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 2;
  inline ::google::protobuf::uint64 time() const;
  inline void set_time(::google::protobuf::uint64 value);
  
  // repeated .kodiaq_data.Event.Module module = 3;
  inline int module_size() const;
  inline void clear_module();
  static const int kModuleFieldNumber = 3;
  inline const ::kodiaq_data::Event_Module& module(int index) const;
  inline ::kodiaq_data::Event_Module* mutable_module(int index);
  inline ::kodiaq_data::Event_Module* add_module();
  inline const ::google::protobuf::RepeatedPtrField< ::kodiaq_data::Event_Module >&
      module() const;
  inline ::google::protobuf::RepeatedPtrField< ::kodiaq_data::Event_Module >*
      mutable_module();
  
  // @@protoc_insertion_point(class_scope:kodiaq_data.Event)
 private:
  inline void set_has_number();
  inline void clear_has_number();
  inline void set_has_time();
  inline void clear_has_time();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 number_;
  ::google::protobuf::uint64 time_;
  ::google::protobuf::RepeatedPtrField< ::kodiaq_data::Event_Module > module_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_protBuffDef_2eproto();
  friend void protobuf_AssignDesc_protBuffDef_2eproto();
  friend void protobuf_ShutdownFile_protBuffDef_2eproto();
  
  void InitAsDefaultInstance();
  static Event* default_instance_;
};
// ===================================================================


// ===================================================================

// Event_Module_Channel

// required int32 channelID = 1;
inline bool Event_Module_Channel::has_channelid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Event_Module_Channel::set_has_channelid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Event_Module_Channel::clear_has_channelid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Event_Module_Channel::clear_channelid() {
  channelid_ = 0;
  clear_has_channelid();
}
inline ::google::protobuf::int32 Event_Module_Channel::channelid() const {
  return channelid_;
}
inline void Event_Module_Channel::set_channelid(::google::protobuf::int32 value) {
  set_has_channelid();
  channelid_ = value;
}

// required bytes data = 2;
inline bool Event_Module_Channel::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Event_Module_Channel::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Event_Module_Channel::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Event_Module_Channel::clear_data() {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& Event_Module_Channel::data() const {
  return *data_;
}
inline void Event_Module_Channel::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void Event_Module_Channel::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void Event_Module_Channel::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Event_Module_Channel::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  return data_;
}
inline ::std::string* Event_Module_Channel::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// Event_Module

// required int32 moduleID = 1;
inline bool Event_Module::has_moduleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Event_Module::set_has_moduleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Event_Module::clear_has_moduleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Event_Module::clear_moduleid() {
  moduleid_ = 0;
  clear_has_moduleid();
}
inline ::google::protobuf::int32 Event_Module::moduleid() const {
  return moduleid_;
}
inline void Event_Module::set_moduleid(::google::protobuf::int32 value) {
  set_has_moduleid();
  moduleid_ = value;
}

// repeated .kodiaq_data.Event.Module.Channel channel = 2;
inline int Event_Module::channel_size() const {
  return channel_.size();
}
inline void Event_Module::clear_channel() {
  channel_.Clear();
}
inline const ::kodiaq_data::Event_Module_Channel& Event_Module::channel(int index) const {
  return channel_.Get(index);
}
inline ::kodiaq_data::Event_Module_Channel* Event_Module::mutable_channel(int index) {
  return channel_.Mutable(index);
}
inline ::kodiaq_data::Event_Module_Channel* Event_Module::add_channel() {
  return channel_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::kodiaq_data::Event_Module_Channel >&
Event_Module::channel() const {
  return channel_;
}
inline ::google::protobuf::RepeatedPtrField< ::kodiaq_data::Event_Module_Channel >*
Event_Module::mutable_channel() {
  return &channel_;
}

// -------------------------------------------------------------------

// Event

// required int64 number = 1;
inline bool Event::has_number() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Event::set_has_number() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Event::clear_has_number() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Event::clear_number() {
  number_ = GOOGLE_LONGLONG(0);
  clear_has_number();
}
inline ::google::protobuf::int64 Event::number() const {
  return number_;
}
inline void Event::set_number(::google::protobuf::int64 value) {
  set_has_number();
  number_ = value;
}

// required uint64 time = 2;
inline bool Event::has_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Event::set_has_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Event::clear_has_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Event::clear_time() {
  time_ = GOOGLE_ULONGLONG(0);
  clear_has_time();
}
inline ::google::protobuf::uint64 Event::time() const {
  return time_;
}
inline void Event::set_time(::google::protobuf::uint64 value) {
  set_has_time();
  time_ = value;
}

// repeated .kodiaq_data.Event.Module module = 3;
inline int Event::module_size() const {
  return module_.size();
}
inline void Event::clear_module() {
  module_.Clear();
}
inline const ::kodiaq_data::Event_Module& Event::module(int index) const {
  return module_.Get(index);
}
inline ::kodiaq_data::Event_Module* Event::mutable_module(int index) {
  return module_.Mutable(index);
}
inline ::kodiaq_data::Event_Module* Event::add_module() {
  return module_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::kodiaq_data::Event_Module >&
Event::module() const {
  return module_;
}
inline ::google::protobuf::RepeatedPtrField< ::kodiaq_data::Event_Module >*
Event::mutable_module() {
  return &module_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace kodiaq_data

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protBuffDef_2eproto__INCLUDED
